"""常量定义"""

from constants.constants import (
    CONFIG_KEY_SELECTION_STRATEGY,
    CONFIG_KEY_POOL_SIZE,
    DEFAULT_POOL_SIZE,
    PROVIDER_OPENAI,
    PROVIDER_ANTHROPIC,
    OPENAI_API_URL,
    OPENAI_API_VERSION,
    ANTHROPIC_API_URL,
    ANTHROPIC_API_VERSION,
    DEFAULT_USER_AGENT,
    DEFAULT_ACCEPT_LANGUAGE,
)

from constants.models import (
    OPENAI_MODELS,
    ANTHROPIC_MODELS,
    MODEL_TO_PROVIDER,
    get_provider_by_model,
)

__all__ = [
    'CONFIG_KEY_SELECTION_STRATEGY',
    'CONFIG_KEY_POOL_SIZE',
    'DEFAULT_POOL_SIZE',
    'PROVIDER_OPENAI',
    'PROVIDER_ANTHROPIC',
    'OPENAI_API_URL',
    'OPENAI_API_VERSION',
    'ANTHROPIC_API_URL',
    'ANTHROPIC_API_VERSION',
    'DEFAULT_USER_AGENT',
    'DEFAULT_ACCEPT_LANGUAGE',
    'OPENAI_MODELS',
    'ANTHROPIC_MODELS',
    'MODEL_TO_PROVIDER',
    'get_provider_by_model',
]

